import Link from "next/link";
import Image from "next/image";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { ProjectVisual } from "@/components/project-visual";
import { Reveal } from "@/components/reveal";
import { Button } from "@/components/ui/button";
import { projects } from "@/data/projects";
import { profile } from "@/data/profile";

export default function Home() {
  return <><SiteHeader /><main id="main">
    <section className="mx-auto grid min-h-[calc(100svh-4rem)] max-w-7xl content-center px-5 py-20 lg:grid-cols-12 lg:px-8">
      <div className="lg:col-span-9"><Reveal><p className="eyebrow mb-8">Independent product engineer · Available for select collaborations</p></Reveal><Reveal delay={.06}><h1 className="max-w-5xl font-display text-5xl leading-[.98] tracking-[-.045em] text-ink sm:text-7xl lg:text-[92px]">I design <em className="font-normal text-moss">intelligent systems</em> that make complex work feel clear.</h1></Reveal><Reveal delay={.12}><p className="mt-8 max-w-xl text-lg leading-relaxed text-ink/65">AI Automation Engineer, Full Stack Engineer, Product Thinker, and System Designer. I bring product judgment to the layer where AI meets real operational work.</p></Reveal><Reveal delay={.18}><div className="mt-10 flex flex-wrap gap-3"><Button asChild><Link href="#work">Selected work <ArrowDownRight size={16} /></Link></Button><Button asChild variant="outline"><a href={`mailto:${profile.email}`}>Start a conversation <ArrowUpRight size={16} /></a></Button></div></Reveal></div>
      <div className="mt-14 grid grid-cols-2 gap-3 border-t border-ink/10 pt-5 text-sm lg:col-span-12 lg:mt-20 lg:grid-cols-4"><div><p className="text-ink/45">Focus</p><p className="mt-1 font-medium">Agentic workflows</p></div><div><p className="text-ink/45">Practice</p><p className="mt-1 font-medium">Product engineering</p></div><div><p className="text-ink/45">Approach</p><p className="mt-1 font-medium">Evidence over novelty</p></div><div><p className="text-ink/45">Based in</p><p className="mt-1 font-medium">{profile.location}</p></div></div>
    </section>

    <section id="work" className="border-t border-ink/10 px-5 py-20 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow">Selected work</p><h2 className="mt-3 max-w-xl font-display text-4xl tracking-[-.035em] sm:text-5xl">Systems built around the people who use them.</h2></div><p className="hidden max-w-xs text-sm leading-relaxed text-ink/60 md:block">Every project begins with a human workflow, then earns its technology through measurable usefulness.</p></div></Reveal>
      <div className="space-y-20 lg:space-y-32">{projects.map((project, index) => <Reveal key={project.slug}><article className={`grid items-center gap-8 lg:grid-cols-2 lg:gap-16 ${index % 2 ? "lg:[&>*:first-child]:order-2" : ""}`}><Link href={`/work/${project.slug}`} aria-label={`Read ${project.name} project overview`} className="group block"><ProjectVisual variant={index} priority={index === 0} /></Link><div className="max-w-lg"><p className="eyebrow">{project.number} · {project.category}</p><h3 className="mt-3 font-display text-4xl tracking-[-.035em] sm:text-5xl">{project.name}</h3><p className="mt-5 text-lg leading-relaxed text-ink/65">{project.summary}</p><div className="mt-7 inline-flex items-center gap-3 border-l-2 border-moss pl-3 text-sm font-medium text-moss">{project.status}</div><Link className="mt-9 inline-flex items-center gap-2 text-sm font-semibold underline decoration-ink/25 underline-offset-4 transition hover:decoration-ink" href={`/work/${project.slug}`}>View project <ArrowUpRight size={15} /></Link></div></article></Reveal>)}</div></div></section>

    <section id="systems" className="bg-ink px-5 py-20 text-paper lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-12"><Reveal className="lg:col-span-5"><p className="eyebrow text-[#9dc9b6]">What&apos;s next at Wong Studio</p><h2 className="mt-3 font-display text-4xl tracking-[-.035em] sm:text-5xl">A foundation built to keep evolving.</h2></Reveal><Reveal delay={.08} className="lg:col-span-6 lg:col-start-7"><figure className="relative aspect-[4/3] overflow-hidden rounded-xl border border-paper/15 bg-paper/5"><Image src="/projects/wong-studio-future.png" alt="Concept visual for what is next at Wong Studio" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></figure><p className="mt-6 max-w-xl text-lg leading-relaxed text-paper/70">Wong Studio is being shaped as a flexible platform for new work, stronger systems, and more considered product experiences.</p></Reveal></div></section>

      <section id="about" className="px-5 py-20 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-12"><Reveal className="lg:col-span-4"><p className="eyebrow">About</p><h2 className="mt-3 font-display text-4xl tracking-[-.035em] sm:text-5xl">A technical partner with product instincts.</h2></Reveal><Reveal delay={.08} className="lg:col-span-6 lg:col-start-7"><p className="text-xl leading-relaxed text-ink/70">I work across research, interaction design, full-stack development, and applied AI to make useful things real. My strongest work creates shared clarity—between users, teams, systems, and decisions.</p><div className="mt-10 flex flex-wrap gap-x-8 gap-y-4 text-sm"><a className="font-semibold underline underline-offset-4" href={`mailto:${profile.email}`}>{profile.email}</a><a className="text-ink/65 hover:text-ink" href="#work">View selected work</a><a className="text-ink/65 hover:text-ink" href={`mailto:${profile.email}?subject=R%C3%A9sum%C3%A9%20request`}>Request résumé</a></div></Reveal></div></section>
  </main><SiteFooter /></>;
}
